#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/sibtree
#
# IDENTIFICATION
#    src/backend/access/sibtree/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/sibtree
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	sibtpage.o \
	sibtree.o \
	sibtsearch.o \
	sibtsort.o

include $(top_srcdir)/src/backend/common.mk
